export const DISCLAIMER = "盘中估值，仅供参考，不等同官方净值";

export const ERROR_CODES = {
  FUND_NOT_FOUND: "FUND_NOT_FOUND",
  ESTIMATE_NOT_READY: "ESTIMATE_NOT_READY",
  INVALID_FUND_CODES: "INVALID_FUND_CODES",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_DISABLED: "USER_DISABLED",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",
  INVALID_PORTFOLIO: "INVALID_PORTFOLIO",
  PORTFOLIO_NOT_FOUND: "PORTFOLIO_NOT_FOUND",
  PORTFOLIO_FUND_NOT_FOUND: "PORTFOLIO_FUND_NOT_FOUND",
  DUPLICATE_PORTFOLIO_NAME: "DUPLICATE_PORTFOLIO_NAME",
  SHARE_NOT_AVAILABLE: "SHARE_NOT_AVAILABLE",
  SHARE_PASSWORD_REQUIRED: "SHARE_PASSWORD_REQUIRED",
  SHARE_PASSWORD_INVALID: "SHARE_PASSWORD_INVALID",
  INVALID_DECISION_AI_CONFIG: "INVALID_DECISION_AI_CONFIG",
  DECISION_AI_CONFIG_REQUIRED: "DECISION_AI_CONFIG_REQUIRED",
  DECISION_DOC_NOT_FOUND: "DECISION_DOC_NOT_FOUND",
  DECISION_GENERATION_FAILED: "DECISION_GENERATION_FAILED",
  DATA_SOURCE_UNAVAILABLE: "DATA_SOURCE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export const ASIA_SHANGHAI_TIMEZONE = "Asia/Shanghai";
